### ISSUE TITLE
[Bug] Crash when joining skyblock

### ISSUE THREAD

**Issue by Gamemine098** [Fix3dll/SkyblockAddons#74] opened 2024-11-08 13:51 UTC
### Bug Description

Game crash when VanillaHub install after update sba to beta 20

### SBA Version

1.9.0-beta.20

### Other Installed Mods

VanillaHUD-1.8.9-forge-2.2.10

### Operating System

Windows 11

### Crash Report

[crash-2024-11-08_20.45.17-client.txt](https://github.com/user-attachments/files/17679533/crash-2024-11-08_20.45.17-client.txt)

**Comment by Fix3dll** [comment] 2024-11-08 14:02
Duplicate of https://github.com/Fix3dll/SkyblockAddons/issues/73

**Closed by Fix3dll** 2024-11-08 14:02 UTC
Labels: bug
