### ISSUE TITLE
[Bug] Enchant Tooltip

### ISSUE THREAD

**Issue by Triggered0** [Fix3dll/SkyblockAddons#36] opened 2024-04-23 10:54 UTC
### Bug Description

Enchant colors conflicts with /neuec

SBA Parse Enchant Tooltips 

Turned off
![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/6499a2da-9c57-4aaf-a248-79198a8d597a)

Turned on
![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/1837008b-369d-4356-848d-9563adaacdca)

### SBA Version

1.9.0-beta.3+251-for-MC-1.8.9

### Other Installed Mods

![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/3333846d-c243-48bb-9403-2da5c3c9fabc)

### Operating System

Wİndows 10

**Comment by Fix3dll** [comment] 2024-04-23 11:10
@Triggered0 Did you close this subsetting? Its old behaviour of SBA
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/f4e0e3fa-c1db-408d-82a1-72b1d672b852)

**Comment by Triggered0** [comment] 2024-04-23 11:13
oh i dont know how but my max tier color was changed but still if change the preset from neuec it doesnt apply

**Comment by Triggered0** [comment] 2024-04-23 11:15
![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/3c93a11b-de57-4159-a5bc-855b73bb34f6)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/57991380/6305cdbf-8290-45b5-8d70-d4f9e039319e)

**Comment by Fix3dll** [comment] 2024-04-23 11:19
@Triggered0 Its intended behaviour for old SBA. Its not a bug but i will look this for next version. 
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/e493d877-a60d-4003-87a0-9f818b510ec5)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/68122184-1343-42ae-8c1f-2bbfbb8626fb)
Then close the setting.

**Closed** 2024-04-23 11:23 UTC
Labels: bug
